=== mraheigvd/LABO2_SER/PLEX-Admin/SER_Labo1_PLEX_ADMIN.dtd
<!ELEMENT Main (Acteurs, Films, Projections) >

<!ELEMENT Acteurs (Acteur)*>
<!ELEMENT Films (Film)*>
<!ELEMENT Projections (Projection)*>

<!-- Balise second niveau -->
<!ELEMENT Acteur (Nom, Nom_Naissance, Biographie, Sexe, Date_Naissance, Date_Deces)>
<!ELEMENT Film (Film_Acteurs, Titre, Synopsis, Duree, Genres, Photo, Critiques, Keywords, Langages)>
<!ELEMENT Projection (Date, Salle, Projection_Film)>

<!-- Balise Acteur -->
<!ATTLIST Acteur id ID #REQUIRED>
<!ELEMENT Nom  (#PCDATA)>
<!ELEMENT Nom_Naissance  (#PCDATA)>
<!ELEMENT Biographie  (#PCDATA)>
<!ELEMENT Sexe  (#PCDATA)>
<!ELEMENT Date_Naissance  (#PCDATA)>
<!ELEMENT Date_Deces  (#PCDATA)>

<!-- Balise Film -->
<!ATTLIST Film id ID #REQUIRED>
<!ELEMENT Film_Acteurs  (Film_Acteur)*>
<!ELEMENT Titre  (#PCDATA)>
<!ELEMENT Synopsis  (#PCDATA)>
<!ELEMENT Duree  (#PCDATA)>
<!ELEMENT Genres  (Genre)*>
<!ELEMENT Photo EMPTY>
<!ELEMENT Critiques  (Critique)*>
<!ELEMENT Keywords  (Keyword)*>
<!ELEMENT Langages  (Langage)*>

<!ATTLIST Photo url CDATA #REQUIRED>

<!-- Balise Film_Acteur -->
<!ATTLIST Film_Acteur id IDREF #REQUIRED>
<!ELEMENT Film_Acteur (Role_Nom, Role_Place)>

<!-- Balise Film_Acteur -->
<!ELEMENT Role_Nom  (#PCDATA) >
<!ELEMENT Role_Place  (#PCDATA) >

<!ELEMENT Genre  (#PCDATA)>

<!-- Balise Critique, Keyword & Langage -->
<!ELEMENT Critique  (Texte, Note)>
<!ELEMENT Keyword  (#PCDATA)>
<!ELEMENT Langage  (#PCDATA)>

<!-- Balise Critique -->
<!ELEMENT Texte  (#PCDATA)>
<!ELEMENT Note  (#PCDATA)>

<!-- Balise Projection -->
<!ELEMENT Date  (#PCDATA) >
<!ELEMENT Salle  (#PCDATA) >
<!ELEMENT Projection_Film EMPTY>
<!ATTLIST Projection_Film id IDREF #REQUIRED>

=== mraheigvd/LABO2_SER/PLEX-Admin/SER_Labo2_PLEX_ADMIN.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Main PUBLIC "SYSTEM" "SER_Labo1_PLEX_ADMIN.dtd">
<Main>
  <Acteurs>
    <Acteur id="id_2242968">
      <Nom>Du Jeu, Félicité</Nom>
      <Nom_Naissance />
      <Biographie />
      <Sexe>FEMININ</Sexe>
      <Date_Naissance />
      <Date_Deces />
    </Acteur>
    <Acteur id="id_2667303">
      <Nom>Murino, Caterina</Nom>
      <Nom_Naissance />
      <Biographie>Caterina Murino was born on September 15, 1977, in Cagliari, Sardinia, Italy. In 1996 she reached the fourth place in the Miss Italy contest. Then she moved to Milan where she began working as a model in commercials for Mastercard, Swatch, Mercedes Benz, and Nescafe among other gigs. From 1999-2000 she studied acting at the Scuola di Cinema e Teatro di Francesca de Sapio in Italy.  In 1999, Murino made her acting debut in a stage production of Richard III and also in several Italian language plays. In 2002 she began her film and television career with playing bit parts in Italian, German, and French productions. Her breakthrough came in 2004, when she co-starred opposite 'Jean Reno (I)' (qv) in a French comedy _L'enquête corse (2004)_ (qv).  Ms. Murino is trilingual, she speaks French and English in addition to her native Italian. She is a versatile actress and a good athlete. Her talents include singing, dancing tango, flamenco and oriental dances, as well as horseback riding. She is co-starring as Solange, one of three Bond girls, opposite 'Daniel Craig (I)' (qv) in _Casino Royale (2006)_ (qv).</Biographie>
      <Sexe>FEMININ</Sexe>
      <Date_Naissance>15-09-1977 - 12:00</Date_Naissance>
      <Date_Deces />
    </Acteur>
    <Acteur id="id_2401856">
      <Nom>Hladikova, Veronika</Nom>
      <Nom_Naissance />
      <Biographie />
      <Sexe>FEMININ</Sexe>
      <Date_Naissance />
      <Date_Deces />
    </Acteur>
    <Acteur id="id_295903">
      <Nom>Chadbon, Tom</Nom>
      <Nom_Naissance />
      <Biographie />
      <Sexe>MASCULIN</Sexe>
      <Date_Naissance>27-02-1946 - 12:00</Date_Naissance>
      <Date_Deces />
    </Acteur>
    <Acteur id="id_2702533">
      <Nom>Ochotská, Michaela</Nom>
      <Nom_Naissance />
      <Biographie />
      <Sexe>FEMININ</Sexe>
      <Date_Naissance>19-12-1984 - 12:00</Date_Naissance>
      <Date_Deces />
    </Acteur>
    <Acteur id="id_1583928">
      <Nom>Schick, Clemens</Nom>
      <Nom_Naissance />
      <Biographie />
      <Sexe>MASCULIN</Sexe>
      <Date_Naissance>15-02-1972 - 12:00</Date_Naissance>
      <Date_Deces />
    </Acteur>
    <Acteur id="id_2248252">
      <Nom>Duravolá, Martina</Nom>
      <Nom_Naissance />
      <Biographie />
      <Sexe>FEMININ</Sexe>
      <Date_Naissance />
      <Date_Deces />
    </Acteur>
    <Acteur id="id_2379317">
      <Nom>Hartford, Diane</Nom>
      <Nom_Naissance />
      <Biographie />
      <Sexe>FEMININ</Sexe>
      <Date_Naissance />
      <Date_Deces />
    </Acteur>
    <Acteur id="id_398765">
      <Nom>Daniel, Andreas</Nom>
      <Nom_Naissance />
      <Biographie />
      <Sexe>MASCULIN</Sexe>
      <Date_Naissance />
      <Date_Deces />
    </Acteur>
    <Acteur id="id_1403596">
      <Nom>Pistor, Ludger</Nom>
      <Nom_Naissance />
      <Biographie />
      <Sexe>MASCULIN</Sexe>
      <Date_Naissance>16-03-1959 - 12:00</Date_Naissance>
      <Date_Deces />
    </Acteur>
    <Acteur id="id_1007099">
      <Nom>Leal, Carlos</Nom>
      <Nom_Naissance />
      <Biographie />
      <Sexe>MASCULIN</Sexe>
      <Date_Naissance>01-01-1969 - 12:00</Date_Naissance>
      <Date_Deces />
    </Acteur>
    <Acteur id="id_488415">
      <Nom>Durran, Jason</Nom>
      <Nom_Naissance />
      <Biographie />
      <Sexe>MASCULIN</Sexe>
      <Date_Naissance />
      <Date_Deces />
    </Acteur>
    <Acteur id="id_1199473">
      <Nom>Millson, Joseph</Nom>
      <Nom_Naissance />
      <Biographie />
      <Sexe>MASCULIN</Sexe>
      <Date_Naissance>01-01-1974 - 12:00</Date_Naissance>
      <Date_Deces />
    </Acteur>
    <Acteur id="id_1559434">
      <Nom>Sammel, Richard</Nom>
      <Nom_Naissance />
      <Biographie>Born in Heidelberg; a curious and shy boy; found the key for his world through passion for music, dance and theater; Richard studied music and drama in Germany, acting and direction in France and method acting with Susan Strasberg and Francesca de Sapio in Italy. He first went on stage in 1981 at the local theater Hildesheim, then, from 1983 in France on independent stages, at national theaters and in the streets. In 1989 he moved to Italy and met Susan Strasberg: His cinema debut was in 1990 starring in "Il Piacere delle Carni" by Barbara Barni. In 1993, he moved to Paris and got the leading role in the film version of Brechts/Eislers" The Lindbergh's Flight". Since then he has worked on film, television, theater and dance productions all over Europe, in Canada, South Africa, USA, Macedonia, Morocco which brought him happiness and a lot of richly diversified creative and thrilling experiences Richard lives in Berlin and Paris since 2007. He speaks 5 languages fluently, travels a lot and loves to be challenged.</Biographie>
      <Sexe>MASCULIN</Sexe>
      <Date_Naissance>01-01-1960 - 12:00</Date_Naissance>
      <Date_Deces />
    </Acteur>
    <Acteur id="id_1748274">
      <Nom>Tarrach, Jürgen</Nom>
      <Nom_Naissance />
      <Biographie />
      <Sexe>MASCULIN</Sexe>
      <Date_Naissance>17-12-1960 - 12:00</Date_Naissance>
      <Date_Deces />
    </Acteur>
    <Acteur id="id_2153316">
      <Nom>Chin, Tsai</Nom>
      <Nom_Naissance>Zhou, Tsai Chin</Nom_Naissance>
      <Biographie>Tsai Chin, pinyin Zhou Caiqin is an actor, director, teacher and author, best known in America for her film role as Auntie Lindo in The Joy Luck Club. The third daughter of Zhou Xinfang, China's great actor in the last century, she was trained at the Royal Academy of Dramatic Art London (first Chinese student) and later earned a Master Degree at Tufts University, Boston. Her career spans more than five decades working in UK, USA and recently in China. She starred on stage on both sides of the atlantic, (a first for a Chinese actor) in London's West End,The World of Susie Wong and on Broadway, Golden Child; played the two most powerful women of 20th century China; for television, in The Subject of Struggle; for stage Memories of Madame Mao; was twice in Bond films, as Bond girl in You Only Live Twice, and later in Casino Royale. Her single The Ding Dong Song recorded for Decca was top of the charts in Asia. She was the first to be invited to teach acting in China after the Cultural Revolution when universities re-opened. She is now celebrated in China for her portrayal of Jia Mu in the recent TV drama series, The Dream of The Red Chamber. Her international best-selling autobiography, Daughter of Shanghai is to be a stage play by David Henry Hwang which will be produced by the Wallis Annenberg Center for the Perfoming Arts in Beverly Hills.</Biographie>
      <Sexe>FEMININ</Sexe>
      <Date_Naissance>30-11-1936 - 12:00</Date_Naissance>
      <Date_Deces />
    </Acteur>
    <Acteur id="id_1298032">
      <Nom>Notley, Peter</Nom>
      <Nom_Naissance />
      <Biographie />
      <Sexe>MASCULIN</Sexe>
      <Date_Naissance />
      <Date_Deces />
    </Acteur>
    <Acteur id="id_968243">
      <Nom>Kulhavý, Vladimír</Nom>
      <Nom_Naissance />
      <Biographie />
      <Sexe>MASCULIN</Sexe>
      <Date_Naissance />
      <Date_Deces />
    </Acteur>
    <Acteur id="id_1812821">
      <Nom>Ucík, Martin</Nom>
      <Nom_Naissance />
      <Biographie />
      <Sexe>MASCULIN</Sexe>
      <Date_Naissance>05-12-1955 - 12:00</Date_Naissance>
      <Date_Deces />
    </Acteur>
    <Acteur id="id_1179146">
      <Nom>Menzies, Tobias</Nom>
      <Nom_Naissance />
      <Biographie>Tobias was born in London. He graduated from the Royal Academy of Dramatic Art (RADA) in 1998 and began his acting career in popular UK series such as Foyle's War, Midsomer Murders, and Casualty. He also appeared in the controversial drama A Very Social Secretary. He is best known to international audiences as Marcus Junius Brutus in the television series Rome.  He had a major film role in The Low Down with Aidan Gillen and featured in the 2006 reboot of the James Bond franchise, Casino Royale. 2007 sees him appearing as William Elliot in ITV's production of Jane Austin's classic book, Persuasion and as Derrick Sington in the Channel 4 drama The Relief of Belsen.  On stage, his credits include the young teacher Irwin in Alan Bennett's The History Boys and Michael Blakemore's West End production of Three Sisters for which he was nominated for the Ian Charleson Award. He was a critically acclaimed Hamlet in Rupert Goold's Hamlet at the Royal Theatre.</Biographie>
      <Sexe>MASCULIN</Sexe>
      <Date_Naissance>07-03-1974 - 12:00</Date_Naissance>
      <Date_Deces />
    </Acteur>
    <Acteur id="id_2325595">
      <Nom>Gethings, Rebecca</Nom>
      <Nom_Naissance />
      <Biographie />
      <Sexe>FEMININ</Sexe>
      <Date_Naissance />
      <Date_Deces />
    </Acteur>
    <Acteur id="id_1941794">
      <Nom>Wright, Jeffrey</Nom>
      <Nom_Naissance />
